name: Manga Check (scheduled)

on:
  schedule:
    - cron: "*/30 * * * *"  # cada 30 minutos (no garantizado exacto)
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        id: scrape
        run: |
          python unified_manga_scraper.py --library manga_library.yaml --check --report updates.json || echo "exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Post to Discord (if updates)
        if: always()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python notify_discord.py updates.json || true

      - name: Update baseline (only on manual run)
        if: github.event_name == 'workflow_dispatch'
        run: |
          python unified_manga_scraper.py --library manga_library.yaml --check --save
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manga_library.yaml
          git commit -m "chore: update last_seen baseline [skip ci]" || echo "No changes"
          git push
