name: Manga Check

on:
  workflow_dispatch:
    inputs:
      bootstrap:
        description: "Seed/Bootstrap: guarda el último capítulo sin notificar"
        required: false
        default: "false"
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run unified scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event.inputs.bootstrap }}" = "true" ]; then
            python unified_manga_scraper.py --bootstrap || true
          else
            python unified_manga_scraper.py --discord "${DISCORD_WEBHOOK_URL}" || true
          fi

      - name: Commit state if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "Update state"
          git push
