name: Manga Check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unified scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PROXY_URL: ${{ secrets.PROXY_URL }}  # opcional
        run: |
          python unified_manga_scraper.py || true

      - name: Commit state if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet manga_library.yml; then
            git add manga_library.yml
            git commit -m "update: last_chapter auto"
            git push
          else
            echo "No changes to commit."
          fi
